---
Expression: bulkmodulus("wurtzite_lattopt")
Weight: 1
ReferenceValue: 129
---
Expression: lattice("wurtzite_lattopt", 0)
Weight: 1
ReferenceValue: 3.29
---
Expression: lattice("wurtzite_lattopt", 2)
Weight: 1
ReferenceValue: 5.31
---
Expression: energy("wurtzite_lattopt")/2.0-energy("rocksalt_lattopt")
Weight: 1
ReferenceValue: -0.011024953143949138
...
# 0.5.0
